# using this approach https://github.com/jsakamoto/PublishSPAforGitHubPages.Build
# which also uses this: https://github.com/peaceiris/actions-gh-pages
# Different approach here: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly/github-pages?view=aspnetcore-9.0

name: github pages

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      # Publish the site
      # additional details handled by https://github.com/jsakamoto/PublishSPAforGitHubPages.Build
      - name: Publish
        run: dotnet publish ExistHelper.sln -c:Release -o:publish -p:GHPages=true

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true